### ISSUE TITLE
Feature request: new behavior markers

### ISSUE THREAD

**Issue by boazmohar** [thatJavaNerd/spinevis#4]
I have a new experiment where the current behavior markers are not compatible.
I saw that currently they are being fed from [here](https://github.com/mattbdean/spinevis/blob/develop/app/client/src/timeline/markers.js), to [here](https://github.com/mattbdean/spinevis/blob/develop/app/client/src/timeline/timeline.component.js#L175).

One way to add new markers would be to edit that file.
Another way would be to add those fields to each marker in the behavior table. 
```json
{
    "srcID": 0,
    "volNums": [0,1,2],
    "evtType":  "name",
    "symbol": "triangle-down",
    "color": "red"
}
```
Or make a new table in the database (markers) where we can make these mappings: name --> (symbol, color).

@mattbdean What do you think?

**Comment by mattbdean** [comment]
What isn't compatible? Is it just the names or is it also the symbols and colors?

**Comment by boazmohar** [comment]
All of the above, I need different name symbols and colors.

**Comment by mattbdean** [comment]
Here's a solution:

- [x] Remove `markers.js`
- [x] Edit the current behavior collection so that it looks like this:

```json
{
    "srcID": 0,
    "volNums": [0,1,2],
    "evtType":  "name",
    "marker": {
        "symbol": "triangle-down",
        "color": "red"
    }
}
```

- [x] Have `queries.getBehavior` return the actual document instead of transforming it beforehand
- [x] Update the client-side code for this API change
